title: Alperen INAL
description: "Software engineer at Iyzico — tech guy"
author: "Alperen INAL"
github: apollo629
twitter: alpereninall
email: inal.alperen@gmail.com
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"

about:
  - name: Github
    username: apollo629
    url: https://github.com/apollo629
    class: github
  - name: Twitter
    username: alpereninall
    url: https://twitter.com/alpereninall
    class: twitter
  - name: Email
    username: inal.alperen@gmail.com
    class: email
    url: mailto:inal.alperen@gmail.com
