title: Alperen INAL
description: "Software engineer at Iyzico — tech guy"
author: "Alperen INAL"
github: apollo629
twitter: alpereninall
email: inal.alperen@gmail.com
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
